# Brick DVC stages
# See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use 
# dvc repro -f
# Individual stage can be executed using: 
# dvc repro <stage>

stages:
  
  download:
    cmd: python3 stages/01_download.py
    deps:
      - https://reporter.nih.gov/exporter
      - stages/01_download.py
    outs:
      - download
      
  build:
    cmd: python3 stages/02_build.py
    deps:
      - download
      - stages/02_build.py
    outs:
      - brick/nih_reporter.parquet

  build_exporter:
    cmd: stages/03_exporter_build.sh
    deps:
      - download
      - stages/03_exporter_build.sh
    outs:
      - brick/ExPORTER
